ruby:
# Ruby prior to 3.2 is currently linked against libcrypt.so.1 which we want to phase
# out. For details, see:
# https://github.com/conda-forge/linux-sysroot-feedstock/issues/52
# 
# - 2.7
# - 3.1
- 3.2
- 3.3