travis:
  secure:
    BINSTAR_TOKEN: wLwSykONa397pc9xzsVcWASJr4Iyw7vCJHaB/+g8DGD9mlYDi85B8It+R7HxuWbXcapfE/5rywm2+7MAuTry5NT4QBrx2UQrHvFhKCiGt+loyFvQ/kWvjZpAPevav2SbxkN+jTv9R28KJMymRgWUIusGFPrDc4k2Olf0u8E4D1F08W61tSqVhI0++dtY8P+8FUVmKNr6yTtMkbdVvL1xgTMME2bNmaC1IxX9hNeylLTlkoJb0gQe+R8GrA0IusvTL2O/Xshp2DGd2mSt27QDtIYXPp4ByOw413e3NT+pWMAdZDIiQ40j2EmGFMaIxuqvZe/q//7JLQqKwtJ3B+VYxWGyOVAG7z15o1zhQh+feDzj9ffped6dWtC7H4zFf5FgD4d/+OWjCM1YhLZ9Hu8diC78PzPxJYMQIzgcwZdw/zf6Y7LAsPp0YtxjWCgiz5ZFkXd6vAsoxEuAZqbE121cKG3BeRx1DNj+v0pnUWVvIEwe1JUJX3jSadr2DMi3gAori/F67mHKZ6ly0K8t8rGusPD+exZNoLVhbS8Fm17U/lxbobEzsszTzKiBjagUWgXlp842pvdMEgTaAvMinwbPwiE9vgsPalnxS3TlUJ6dAn03GKIvSpBfMK2TrS5Nt1oNC+2sVnA4Dw99p1xUom9l/T2Wiy00rHE/kLBevIW51Eo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
